/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ARangePicker: typeof import('@arco-design/web-vue')['RangePicker']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    FilterForm: typeof import('./src/components/FilterForm/FilterForm.vue')['default']
  }
}
